  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  1
      1      C1      C2      1.33994       0   0   0           -5.44479 
      2      C1      H3      1.09315       0   0   0           -2.79432 
      3      C1      H4      1.09324       0   0   0           -2.76267 
      4      C2      H5      1.09316       0   0   0           -2.79449 
      5      C2      H6      1.09321       0   0   0           -2.76105 
  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  2
      1      C1      C2      1.33994       0   0   0           -5.44876 
      2      C1      H3      1.09315       0   0   0           -2.79932 
      3      C1      H4      1.09324       0   0   0           -2.79707 
      4      C2      H5      1.09316       0   0   0           -2.78927 
      5      C2      H6      1.09321       0   0   0           -2.77854 
