  COOP#  atomMU  atomNU     distance     translation      ICOOP (at) eF   for spin  1
      1      C1      C2      1.33994       0   0   0            0.33167 
      2      C1      H3      1.09315       0   0   0            0.19719 
      3      C1      H4      1.09324       0   0   0            0.19686 
      4      C2      H5      1.09316       0   0   0            0.19717 
      5      C2      H6      1.09321       0   0   0            0.19683 
  COOP#  atomMU  atomNU     distance     translation      ICOOP (at) eF   for spin  2
      1      C1      C2      1.33994       0   0   0            0.33163 
      2      C1      H3      1.09315       0   0   0            0.19722 
      3      C1      H4      1.09324       0   0   0            0.19720 
      4      C2      H5      1.09316       0   0   0            0.19681 
      5      C2      H6      1.09321       0   0   0            0.19677 
